### ISSUE TITLE
TypeError: _unpack_version() takes from 1 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by simonzg** [safe-global/safe-infrastructure#159]
I followed the steps but safe-infrastructure-txs-worker-indexer-1 complains about this error:

```TypeError: _unpack_version() takes from 1 to 5 positional arguments but 6 were given```

Seems like an error related to celery, not sure how to resolve it, the full log looks like this:

```
safe-infrastructure-txs-worker-indexer-1                 | Traceback (most recent call last):
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
safe-infrastructure-txs-worker-indexer-1                 |     self.blueprint.start(self)
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
safe-infrastructure-txs-worker-indexer-1                 |     step.start(parent)
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
safe-infrastructure-txs-worker-indexer-1                 |     return self.obj.start()
safe-infrastructure-txs-worker-indexer-1                 |            ^^^^^^^^^^^^^^^^
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/consumer.py", line 340, in start
safe-infrastructure-txs-rabbitmq-1                       | 2024-09-19 18:20:52.883562+00:00 [info] <0.1647.0> closing AMQP connection (172.23.0.13:38326 -> 172.23.0.5:5672, vhost: '/', user: 'guest', duration: '14ms')
safe-infrastructure-txs-rabbitmq-1                       | 2024-09-19 18:20:52.884545+00:00 [info] <0.1638.0> closing AMQP connection (172.23.0.13:38314 -> 172.23.0.5:5672, vhost: '/', user: 'guest', duration: '29ms')
safe-infrastructure-txs-worker-indexer-1                 |     blueprint.start(self)
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
safe-infrastructure-txs-worker-indexer-1                 |     step.start(parent)
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/celery/worker/consumer/tasks.py", line 31, in start
safe-infrastructure-txs-worker-indexer-1                 |     qos_global = not c.connection.qos_semantics_matches_spec
safe-infrastructure-txs-worker-indexer-1                 |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/kombu/connection.py", line 889, in qos_semantics_matches_spec
safe-infrastructure-txs-worker-indexer-1                 |     return self.transport.qos_semantics_matches_spec(self.connection)
safe-infrastructure-txs-worker-indexer-1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/kombu/transport/pyamqp.py", line 227, in qos_semantics_matches_spec
safe-infrastructure-txs-worker-indexer-1                 |     return version_string_as_tuple(props['version']) < (3, 3)
safe-infrastructure-txs-worker-indexer-1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safe-infrastructure-txs-worker-indexer-1                 |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/text.py", line 47, in version_string_as_tuple
safe-infrastructure-txs-worker-indexer-1                 |     v = _unpack_version(*s.split('.'))
safe-infrastructure-txs-worker-indexer-1                 |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safe-infrastructure-txs-worker-indexer-1                 | TypeError: _unpack_version() takes from 1 to 5 positional arguments but 6 were given
```

**Comment by simonzg** [comment]
This issue is gone after pulling the latest docker images with `docker compose pull`
